cc_library(
    name = "questions",
    srcs = [
        "find_maximum_subarray_recursive.cc", 
        "rotate_matrix_90_deg.cc"
        ], # make a globs here
    hdrs = ["questions.h"],
    visibility = ["//main:__pkg__"],
)