cc_library(
    name = "questions",
    srcs = [
        "find_maximum_subarray_recursive.cc", 
        "rotate_matrix_90_deg.cc",
        "rotate_matrix_n_loop.cc",
        "blackjack.cc",
        "bfs.cc",
        "dfs.cc",
        "anagram_substring_search.cc"
        ], # make a globs here
    hdrs = ["questions.h"],
    visibility = ["//main:__pkg__"],
)

//TODO:
* standalone each file
* add algorithms from algorithm repository
