cc_library(
    name = "sort",
    srcs = [
        "bubble_sort.cc",
        "insertion_sort.cc",
        "merge_sort.cc",
        "fastbit_radix_sort.cc",
        "american_flag_sort.cc"
        ],
    hdrs = [
        "sort_algorithms.h",
        "sort.h"
        ],
    visibility = ["//main:__pkg__"],
)